%export_PLIを一気に回すスクリプト
mats = dir("data/**/*.mat");
keySet = ["kumakura_rest","kumakura_practice","kumakura_boredom","kumakura_flow","kumakura_ultra","kumakura_practice", ...
    "kim_rest","kim_practice","kim_boredom","kim_flow","kim_ultra","kim_practice", ...
    "souma_rest","souma_practice","souma_boredom","souma_flow","souma_ultra","souma_practice", ...
    "fujii_rest","fujii_practice","fujii_boredom","fujii_flow","fujii_ultra","fujii_practice", ...
    "tubota_rest","tubota_practice","tubota_boredom","tubota_flow","tubota_ultra","tubota_practice", ...
    "toki_rest","toki_practice","toki_boredom","toki_flow","toki_ultra","toki_practice", ...
           ];

for i=1:length(mats)
    path = strcat(mats(i).folder,"/", mats(i).name);
    load(path);
    if ~ismember(subject, keySet)
        continue
    end

    run("export_PLI");
end
