%export_PLIを一気に回すスクリプト
mats = dir("data/**/*.mat");
keySet = [
%     "kumakura_rest","kumakura_boredom","kumakura_flow","kumakura_flow_ultra","kumakura_overload", ...
%      "kim_rest","kim_boredom","kim_flow_restart","kim_ultra","kim_overload", ...
%      "souma_rest","souma_boredom","souma_flow","souma_ultra","souma_overload", ...
%      "fujii_rest","fujii_boredom","fujii_flow","fujii_ultra","fujii_overload", ...
%      "tubota_rest","tubota_boredom_restart_impedance","tubota_flow","tubota_ultra","tubota_overload", ...
%      "toki_rest","toki_boredom","toki_flow","toki_ultra","toki_overload", ...
%      "mori_rest","mori_boredom","mori_flow","mori_ultra","mori_overload", ...
%      "hochi_rest","hochi_boredom","hochi_flow","hochi_ultra","hochi_overload", ...
%      "yamada_rest","yamada_boredom","yamada_flow","yamada_ultra","yamada_overload", ...
%      "takei_rest","takei_boredom","takei_flow","takei_ultra","takei_overload", ...
%      "tenshin_rest","tenshin_boredom","tenshin_flow","tenshin_ultra","tenshin_overload", ...
%      "masanori_rest","masanori_boredom","masanori_flow","masanori_flow_ultra","masanori_overload", ...
%      "enoki_rest","enoki_boredom","enoki_flow","enoki_flow_ultra","enoki_overload", ...
%      "ito_rest","ito_boredom","ito_flow","ito_flow_ultra","ito_overload", ...
%      "yoshioka_rest","yoshioka_boredom","yoshioka_flow","yoshioka_flow_ultra","yoshioka_overload", ...
%      "chizuru_rest","chizuru_boredom","chizuru_flow","chizuru_flow_ultra","chizuru_overload", ...
%      "shoki_rest","shoki_boredom","shoki_flow","shoki_ultra","shoki_overload", ...
%      "okada_rest","okada_boredom","okada_flow","okada_ultra","okada_overload", ...
%      "yuzuha_rest","yuzuha_boredom","yuzuha_flow","yuzuha_ultra","yuzuha_overload", ...
%      "hasegawa_rest","hasegawa_boredom","hasegawa_flow","hasegawa_ultra","hasegawa_overload", ...
%      "kanemoto_rest","kanemoto_boredom","kanemoto_flow","kanemoto_ultra","kanemoto_overload", ...
%      "haruna_rest","haruna_boredom","haruna_flow","haruna_ultra","haruna_overload", ...
%      "tamami_rest","tamami_boredom","tamami_flow","tamami_ultra","tamami_overload", ...
%      "arai_rest","arai_boredom","arai_flow","arai_ultra","arai_overload", ...
%      "sugata_rest","sugata_boredom","sugata_flow","sugata_ultra","sugata_overload", ...
%      "yoshikawa_rest","yoshikawa_boredom","yoshikawa_flow","yoshikawa_ultra","yoshikawa_overload", ...
%      "yamashita_rest","yamashita_boredom","yamashita_flow","yamashita_ultra","yamashita_overload", ...
%      "ayaka_rest","ayaka_boredom","ayaka_flow","ayaka_ultra","ayaka_overload", ...
      "chihiro_rest","chihiro_boredom","chihiro_flow","chihiro_ultra","chihiro_overload", ...
      "yuito_rest","yuito_boredom","yuito_flow","yuito_ultra","yuito_overload", ...
      "maiko_rest","maiko_boredom","maiko_flow","maiko_ultra","maiko_overload", ...
            ];

for i=1:length(mats)
    path = strcat(mats(i).folder,"/", mats(i).name);
    load(path);
    if ~ismember(subject, keySet)
        continue
    end

    run("export_PLI");
end

