%export_PLIを一気に回すスクリプト
mats = dir("data/**/*.mat");
keySet = ["kumakura_rest","kumakura_boredom","kumakura_flow","kumakura_flow_ultra","kumakura_overload", ...
     "kim_rest","kim_boredom","kim_flow_restart","kim_ultra","kim_overload", ...
     "souma_rest","souma_boredom","souma_flow","souma_ultra","souma_overload", ...
     "fujii_rest","fujii_boredom","fujii_flow","fujii_ultra","fujii_overload", ...
     "tubota_rest","tubota_boredom_restart_impedance","tubota_flow","tubota_ultra","tubota_overload", ...
     "toki_rest","toki_boredom","toki_flow","toki_ultra","toki_overload", ...
     "mori_rest","mori_boredom","mori_flow","mori_ultra","mori_overload", ...
     "hochi_rest","hochi_boredom","hochi_flow","hochi_ultra","hochi_overload", ...
     "yamada_rest","yamada_boredom","yamada_flow","yamada_ultra","yamada_overload", ...
     "takei_rest","takei_boredom","takei_flow","takei_ultra","takei_overload", ...
     "tenshin_rest","tenshin_boredom","tenshin_flow","tenshin_ultra","tenshin_overload", ...
     "masanori_rest","masanori_boredom","masanori_flow","masanori_flow_ultra","masanori_overload", ...
     "enoki_rest","enoki_boredom","enoki_flow","enoki_flow_ultra","enoki_overload", ...
     "ito_rest","ito_boredom","ito_flow","ito_flow_ultra","ito_overload", ...
     "yoshioka_rest","yoshioka_boredom","yoshioka_flow","yoshioka_flow_ultra","yoshioka_overload", ...
     "chizuru_rest","chizuru_boredom","chizuru_flow","chizuru_flow_ultra","chizuru_overload", ...
            ];

% keySet = ["_rest","_boredom","_flow","_ultra","_overload", ...
%            ];


for i=1:length(mats)
    path = strcat(mats(i).folder,"/", mats(i).name);
    load(path);
    if ~ismember(subject, keySet)
        continue
    end

    run("export_PLI");
end

% "_rest","_boredom","_flow","_ultra","_overload", ...
